[server]
headless = true
enableCORS = false
enableXsrfProtection = false
baseUrlPath = "healthcare/SLB24"
port = 5000
address = "0.0.0.0"

[browser]
serverAddress = "caliber360ai.com"
gatherUsageStats = false
